// 'use client';

import type { Metadata } from "next";
import ThemeWrapper from "./components/ThemeWrapper";
import ThemeToggle from "./components/ThemeToggle";
import BackButton from "./components/BackButton";
import ParallaxBackground from "./components/ParallaxBackground";
import "./globals.css";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Project Red Queen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-rq-black dark:bg-rq-blue">
        <ParallaxBackground />
        <div className="relative z-10">
          <ThemeWrapper>
            {/* Navigation */}
            <nav
              role="navigation"
              className="bg-rq-blue dark:bg-rq-black shadow-md py-4 px-4 fixed top-0 w-full z-20"
            >
              <div className="max-w-4xl mx-auto flex justify-between items-center">
                <div className="flex items-center">
                  <BackButton />
                  <a href="#" className="text-xl font-bold text-white">
                    RQ.ai
                  </a>
                </div>
                <div className="flex items-center">
                  <ThemeToggle />
                </div>
              </div>
            </nav>
            <main className="pt-16">{children}</main>
            {/* Footer Section */}
            <Footer />
          </ThemeWrapper>
        </div>
      </body>
    </html>
  );
}
