// 'use client';

import type { Metadata } from "next";
import ThemeWrapper from "./components/ThemeWrapper";
import ThemeToggle from "./components/ThemeToggle";
import BackButton from "./components/BackButton";
import "./globals.css";

export const metadata: Metadata = {
  title: "Project Red Queen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-gray-100 dark:bg-gray-900">
        <ThemeWrapper>
          {/* Navigation */}
          <nav
            role="navigation"
            className="bg-white dark:bg-gray-800 shadow-md py-4 px-4 fixed top-0 w-full z-10"
          >
            <div className="max-w-4xl mx-auto flex justify-between items-center">
              <div className="flex items-center">
                <BackButton />
                <a href="#" className="text-xl font-bold text-gray-900 dark:text-white">
                  Logo
                </a>
              </div>
              <div className="flex items-center">
                <ThemeToggle />
              </div>
            </div>
          </nav>
          <main className="pt-16">{children}</main>
          {/* Footer Section */}
          <footer
            role="contentinfo"
            className="bg-gray-800 dark:bg-gray-900 text-white py-8 px-4"
          >
            <div className="max-w-4xl mx-auto text-center">
              <p>&copy; 2025 Your Company. All rights reserved.</p>
              <div className="mt-4">
                <a
                  href="#"
                  aria-label="Facebook"
                  className="mx-2 text-white hover:text-blue-400"
                >
                  Facebook
                </a>
                <a
                  href="#"
                  aria-label="Twitter"
                  className="mx-2 text-white hover:text-blue-400"
                >
                  Twitter
                </a>
              </div>
            </div>
          </footer>
        </ThemeWrapper>
      </body>
    </html>
  );
}
