// 'use client';

import type { Metadata } from "next";
import { Exo_2, Fira_Code, Jura, Dancing_Script } from 'next/font/google';
import BackButton from "./components/BackButton";
import ParallaxBackground from "./components/ParallaxBackground";
import "./globals.css";
import Footer from "./components/Footer";

const dancing_script = Dancing_Script({
  subsets: ['latin'],
  variable: '--font-dancing_script',
});

const firaCode = Fira_Code({
  subsets: ['latin'],
  variable: '--font-fira-code',
});

const jura = Jura({
  subsets: ['latin'],
  variable: '--font-jura',
});

export const metadata: Metadata = {
  title: "Project Red Queen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jura.variable} ${dancing_script.variable} min-h-screen bg-rq-black font-jura`}>
        <ParallaxBackground />
        <div className="relative z-10">
          {/* Navigation */}
          <nav
            role="navigation"
            className="bg-rq-black backdrop-blur-lg shadow-md py-4 px-4 fixed top-0 w-full z-20 border-b border-rq-red/20"
          >
            <div className="max-w-4xl mx-auto flex justify-between items-center">
              <div className="flex items-center">
                <BackButton />
                <img src="/icons/RQAI_Logo.png" alt="RQ.ai" className="h-8 w-auto" />
              </div>
            </div>
          </nav>
          <main className="pt-16">{children}</main>
          {/* Footer Section */}
          <div className="backdrop-blur-lg bg-rq-black/90">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
